### PR TITLE
Move languages to config

### PR DESCRIPTION
**Pull request by denisdulici**
..so that anyone can add new and/or change their name easily.

### CODE REVIEW

**Comment by 24aitor** [comment]
What do you think about pass languages to another config file like localizer_languages.php?

Then users will be able to publish individually two config files, and the main config file continues with a clear and simply structure.

**Comment by denisdulici** [comment]
That will make the file clean but force users to jump here and there when they want to change language names, set the allowed_langs etc. Having all settings in one file sounds better to me 😉

**Comment by 24aitor** [comment]
Well, localizer languages, is not really a configuration field, the package will work exactly idem that with languages.json file, only changes the output, that I understand that should be modifiable. So it's the reason what I prefer to implement in a different file, to get the real and important config fields in a clear one.

**Comment by denisdulici** [comment]
In fact, it's a real configuration field as users want to add new languages and/or change the current ones. If you think that it's not a configuration field then you're free to close the PR and keep the languages.json file.

**Comment by 24aitor** [comment]
Don't be upset please, just wanna say that I found interesting your PR, because it should be modifiable, but for reasons I've explained before, I prefer to have it in a different config file! I'll merge this, and make languages modifiable as you wish, but in another file. One more time, don't be upset and keep it up! Thanks!

**Pull request merged**
